main.o: main.cpp /usr/local/openmpi-1.4.5/include/mpi.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/mpicxx.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/constants.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/functions.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/datatype.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/exception.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/op.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/status.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/request.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/group.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/comm.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/win.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/file.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/topology.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/info.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/file_inln.h \
 ../../include/BCMTools.h Config.h ../util/include/ConfigBase.h \
 ../util/include/ConfigFile.h ../../include/Vec3.h \
 ../util/include/RootGrid.h ../util/include/BCMOctree.h \
 ../util/include/RootGrid.h ../util/include/Divider.h \
 ../util/include/Pedigree.h ../util/include/Node.h \
 ../../include/NeighborInfo.h ../../include/BCMTools.h \
 ../util/include/Partition.h ../util/include/SimpleDivider.h \
 ../util/include/Partition.h BoundaryConditionSetter.h \
 ../util/include/BoundaryConditionSetterBase.h \
 ../util/include/BoundaryInfo.h ../util/include/BCMOctree.h \
 ../util/include/BlockFactory.h ../util/include/Block.h \
 ../../include/BlockBase.h ../../include/Vec3.h \
 ../../include/NeighborInfo.h ../../include/DataClass.h \
 ../../include/VCUpdater.h ../../include/PointerSetter.h \
 ../util/include/BoundaryInfo.h \
 ../util/include/BoundaryConditionSetterBase.h ../util/include/Block.h \
 ../../include/BlockManager.h ../../include/BlockBase.h \
 ../../include/CommBuffer.h Solver.h ../../include/Scalar3D.h \
 ../../include/Index3D.h ../../include/Vector3D.h Timing.h
Solver.o: Solver.cpp Solver.h /usr/local/openmpi-1.4.5/include/mpi.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/mpicxx.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/constants.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/functions.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/datatype.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/exception.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/op.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/status.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/request.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/group.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/comm.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/win.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/file.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/topology.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/info.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/file_inln.h \
 ../../include/BCMTools.h Config.h ../util/include/ConfigBase.h \
 ../util/include/ConfigFile.h ../../include/Vec3.h \
 ../util/include/Block.h ../../include/BlockBase.h ../../include/Vec3.h \
 ../../include/BCMTools.h ../../include/NeighborInfo.h \
 ../../include/DataClass.h ../../include/VCUpdater.h \
 ../../include/PointerSetter.h ../util/include/BoundaryInfo.h \
 ../util/include/BCMOctree.h ../util/include/RootGrid.h \
 ../util/include/Divider.h ../util/include/Pedigree.h \
 ../util/include/Node.h ../../include/NeighborInfo.h \
 ../util/include/Partition.h ../../include/BlockManager.h \
 ../../include/BlockBase.h ../../include/CommBuffer.h \
 ../../include/Scalar3D.h ../../include/Index3D.h \
 ../../include/Vector3D.h ../../include/Scalar3DUpdater.h \
 ../../include/Scalar3D.h Timing.h
Timing.o: Timing.cpp Timing.h
ConfigFile.o: ../util/src/ConfigFile.cpp ../util/include/ConfigFile.h
ConfigBase.o: ../util/src/ConfigBase.cpp ../util/include/ConfigBase.h \
 ../util/include/ConfigFile.h /usr/local/openmpi-1.4.5/include/mpi.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/mpicxx.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/constants.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/functions.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/datatype.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/exception.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/op.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/status.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/request.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/group.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/comm.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/win.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/file.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/topology.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/info.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/file_inln.h
BCMOctree.o: ../util/src/BCMOctree.cpp ../util/include/BCMOctree.h \
 ../../include/BCMTools.h ../../include/Vec3.h ../util/include/RootGrid.h \
 /usr/local/openmpi-1.4.5/include/mpi.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/mpicxx.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/constants.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/functions.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/datatype.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/exception.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/op.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/status.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/request.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/group.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/comm.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/win.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/file.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/topology.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/info.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /usr/local/openmpi-1.4.5/include/openmpi/ompi/mpi/cxx/file_inln.h \
 ../util/include/Divider.h ../util/include/Pedigree.h \
 ../util/include/Node.h ../../include/NeighborInfo.h \
 ../../include/BCMTools.h ../util/include/Partition.h
